# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
    NODE_VERSION: "22.x"

on: [push]

jobs:
    lint:
        name: ✅ Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{env.NODE_VERSION}}
            - run: npm ci
            - run: npm run lint --if-present
    test:
        name: Format check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{env.NODE_VERSION}}
            - run: npm ci
            - run: npm run formatCheck --if-present
    typeCheck:
        name: Type Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{env.NODE_VERSION}}
            - run: npm ci
            - run: npm run typeCheck --if-present
