backend:
    name: git-gateway
    branch: main
    commit_messages:
        create: "Create {{collection}} “{{slug}}”"
        update: "Update {{collection}} “{{slug}}”"
        delete: "Delete {{collection}} “{{slug}}”"
        uploadMedia: "[skip ci] Upload “{{path}}”"
        deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
    - name: "cell-line"
      label: "Cell Line"
      folder: "src/pages/cell-line"
      create: true
      slug: "{{cell_line_id}}"
      fields:
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "cell-line",
            }
          - {
                label: "ID",
                name: "cell_line_id",
                widget: "string",
                required: true,
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
                label: "Clone Number",
                name: "clone_number",
                widget: "number",
                valueType: int,
                required: true,
            }
          - {
                label: "Parent line",
                name: "parent_line",
                widget: "string",
                default: "WTC",
            }
          - {
                label: "Gene",
                name: "gene",
                widget: "relation",
                collection: "gene",
                search_fields:
                    ["gene_symbol", "gene_name", "protein", "structure"],
                value_field: "gene_name",
                display_fields: ["gene_symbol", "protein", "structure"],
            }
          - {
                label: "Protein",
                name: "protein",
                widget: "hidden",
            }
          - {
                label: "Allele Count",
                name: "alleleCount",
                widget: "select",
                options: ["mono", "bi"],
                required: false,
            }
          - {
                label: "Status",
                name: "status",
                widget: "select",
                options: ["in progress", "done"],
                default: "in progress",
                required: true,
            }
          - {
                label: "Terminal Tagged",
                name: "terminal_tagged",
                widget: "select",
                options:
                    [
                        "C-terminus",
                        "N-terminus",
                        "C-terminus / N-terminus",
                        "C-terminus / C-terminus / N-terminus",
                    ],
                required: false,
            }
          - {
                label: "Fluorescent Tag",
                name: "fluorescent_tag",
                widget: "select",
                options:
                    [
                        "mEGFP",
                        "EGFP",
                        "mTagRFP-T",
                        "mEGFP / mTagRFP-T",
                        "TagBFP",
                        "mEGFP / mTagRFP-T / HaloTag",
                    ],
                required: false,
            }
          - {
                label: "Linker",
                name: "linker",
                widget: "string",
                required: false,
            }
          - {
                label: "Order Link",
                name: "order_link",
                widget: "string",
                required: false,
            }
    - name: "disease-cell-line"
      label: "Disease Cell Line"
      folder: "src/pages/disease-cell-line"
      create: true
      slug: "{{cell_line_id}}"
      fields:
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "disease-cell-line",
            }
          - {
                label: "ID",
                name: "cell_line_id",
                widget: "string",
                required: true,
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
                label: "Clone Number",
                name: "clone_number",
                widget: "number",
                valueType: int,
                required: true,
            }
          - {
                label: "Parent line",
                name: "parent_line",
                widget: "relation",
                collection: "cell-line",
                search_fields: ["cell_line_id"],
                value_field: "cell_line_id",
            }
          - {
                label: "Gene",
                name: "gene",
                widget: "relation",
                collection: "gene",
                search_fields:
                    ["gene_symbol", "gene_name", "protein", "structure"],
                value_field: "gene_name",
                display_fields: ["gene_symbol", "protein", "structure"],
            }
          - {
                label: "Allele Count",
                name: "alleleCount",
                widget: "select",
                options: ["mono", "bi"],
                required: false,
            }
          - {
                label: "Status",
                name: "status",
                widget: "select",
                options: ["in progress", "done"],
                default: "in progress",
                required: true,
            }
          - {
                label: "Linker",
                name: "linker",
                widget: "string",
                required: false,
            }
          - {
                label: "Order Link",
                name: "order_link",
                widget: "string",
                required: false,
            }
    - name: "gene"
      label: "Gene and structures names"
      folder: "src/pages/gene-names"
      slug: "{{gene_id}}"
      create: true # Allow users to create new documents in this collection
      fields: # The fields each document in this collection have
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "gene-name",
            }
          - {
                label: "Gene Symbol",
                name: "gene_symbol",
                widget: "list",
                required: true,
            }
          - {
                label: "Gene Name",
                name: "gene_name",
                widget: "string",
                required: true,
            }
          - {
                label: "Gene id",
                name: "gene_id",
                widget: "list",
                required: true,
            }
          - {
                label: "Protein",
                name: "protein",
                widget: "string",
                required: true,
            }
          - {
                label: "Structure",
                name: "structure",
                widget: "string",
                required: true,
            }
          - label: "Isoforms"
            name: "isoforms"
            widget: "list"
            required: true
            fields:
                - { label: "Gene name", name: "gene_name", widget: "string" }
                - { label: "Isoforms", name: "isoforms", widget: "list" }

    - name: "pages"
      label: "Pages"
      files:
          - file: "src/pages/index.md"
            label: "Landing Page"
            name: "index"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "index-page",
                  }
                - { label: Title, name: title, widget: string }
                - { label: Image, name: image, widget: image }
                - { label: Subtitle, name: subtitle, widget: string }
                - {
                      label: Mainpitch,
                      name: main_pitch,
                      widget: object,
                      fields:
                          [
                              { label: Title, name: title, widget: string },
                              {
                                  label: Description,
                                  name: description,
                                  widget: text,
                              },
                          ],
                  }
                - {
                      label: Products,
                      name: products,
                      widget: list,
                      fields:
                          [
                              { label: Text, name: text, widget: text },
                              { label: Image, name: image, widget: image },
                          ],
                  }

          - file: "src/pages/about/index.md"
            label: "About"
            name: "about"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "about-page",
                  }
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Body", name: "body", widget: "markdown" }
                - {
                      label: Main,
                      name: main,
                      widget: object,
                      fields:
                          [
                              { label: Heading, name: heading, widget: string },
                              {
                                  label: Description,
                                  name: description,
                                  widget: text,
                              },
                          ],
                  }
                - { label: Full_image, name: full_image, widget: image }
                - {
                      label: Pricing,
                      name: pricing,
                      widget: object,
                      fields:
                          [
                              { label: Heading, name: heading, widget: string },
                              {
                                  label: Description,
                                  name: description,
                                  widget: string,
                              },
                              {
                                  label: Plans,
                                  name: plans,
                                  widget: list,
                                  fields:
                                      [
                                          {
                                              label: Plan,
                                              name: plan,
                                              widget: string,
                                          },
                                          {
                                              label: Price,
                                              name: price,
                                              widget: string,
                                          },
                                          {
                                              label: Description,
                                              name: description,
                                              widget: string,
                                          },
                                          {
                                              label: Items,
                                              name: items,
                                              widget: list,
                                          },
                                      ],
                              },
                          ],
                  }
